# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

development:
  secret_key_base: 7aa314d3c44b3d9f893c5ec0974f5909e930e0e6598c23e415c362cd6929c430d0dffa52a0cf13d979004807c29919c6f24a624bccb3c0291e6f77242b4bc09c
  base_url: 'http://localhost:3000/'